//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamHoangDuy51503613.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=D:\\UNIVERSITY\\DOANKHOALUANTOTNGHIEP\\PHAN" +
            "MEM\\SLT_QL_KARAOKE\\NGUYENTRONGDUY_2201130001\\BIN\\DEBUG\\QLQUANKARAOKE_DATA.MDF;In" +
            "tegrated Security=True")]
        public string D__UNIVERSITY_DOANKHOALUANTOTNGHIEP_PHANMEM_SLT_QL_KARAOKE_NGUYENTRONGDUY_2201130001_BIN_DEBUG_QLQUANKARAOKE_DATA_MDFConnectionString {
            get {
                return ((string)(this["D__UNIVERSITY_DOANKHOALUANTOTNGHIEP_PHANMEM_SLT_QL_KARAOKE_NGUYENTRONGDUY_2201130" +
                    "001_BIN_DEBUG_QLQUANKARAOKE_DATA_MDFConnectionString"]));
            }
        }
    }
}
